import type { Metadata } from "next";
<<<<<<< HEAD
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
=======
import { Geist, Geist_Mono, Figtree } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'
import ErrorBoundary from "./Components/ErrorBoundary";
import AuthHeader from "./Components/AuthHeader";
import "./globals.css";
import { cn } from "../lib/utils";


const figtree = Figtree({subsets:['latin'],variable:'--font-sans'});
>>>>>>> 4e3eac2e6952d52de5eaa3b3b7d4ef86ae6ae188

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
=======
  title: "LogMyClass",
  description: "Smart QR Attendance",
};

export default async function RootLayout({
>>>>>>> 4e3eac2e6952d52de5eaa3b3b7d4ef86ae6ae188
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
=======
    <html lang="en" className={cn("font-sans", figtree.variable)}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClerkProvider
          signInUrl="/sign-in"
          signUpUrl="/sign-up"
          signInFallbackRedirectUrl="/dashboard"
          signUpFallbackRedirectUrl="/dashboard"
        >
          <ErrorBoundary>
            <AuthHeader />
            {children}
          </ErrorBoundary>
        </ClerkProvider>
>>>>>>> 4e3eac2e6952d52de5eaa3b3b7d4ef86ae6ae188
      </body>
    </html>
  );
}
